os: linux-ppc64le

services:
  - docker

before_install:
  - docker pull registry.access.redhat.com/ubi8/ubi:latest
  
script:
  - mkdir out	
  - docker run -v `pwd`:/root/build --workdir=/root/build --name cockroachdb_ubi8 registry.access.redhat.com/ubi8/ubi:latest /bin/bash -c "bash cockroachdb_ubi8.sh"
  - docker cp cockroachdb_ubi8:/cockroachdb_ubi.tar.gz out/
  - docker commit cockroachdb_ubi8 cockroachdb-v19.2.10-ubi8
  - docker ps
  - docker stop cockroachdb_ubi8
  - docker rm cockroachdb_ubi8
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
